name: cd-action

on:
  push:
    branches:
      - main

env:
  CR_URL: ghcr.io
  IMAGE_TAG: ${{ github.sha }}

jobs:
  push-image:
    name: Push a keycloak-distroless image
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: redongjun/repository/keycloak-distroless
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
